version: '3.8'

services:
  simple-api-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple-api-demo-app
    ports:
      - "8080:8080"   # Main server
      - "4242:4242"   # Application server
    environment:
      - RUST_LOG=info
      - PORT=8080
      - PORT_APP=4242
      - BIND_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    container_name: simple-api-demo-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - simple-api-demo
    restart: unless-stopped
    profiles:
      - with-proxy

networks:
  default:
    name: simple-api-demo-network 